version: "3"
services:
        nfs_server:
                build: ./build
                image: drussell1974/nfs-server:release-v0.0.17-alpha
                external_links:
                        - ldap_server
                ports:
                        - 2049:2049
                          #- 111:111
                environment:
                        - NFS_IPADDR_ALLOWED=${NFS_IPADDR_ALLOWED}
                        - NFS_PUBLIC_CONT=${NFS_PUBLIC_CONT}
                        - NFS_HOME_CONT=${NFS_HOME_CONT}

