version: "3"
services:
        nfs_server:
                build: ./build
                image: drussell1974/nfs-server:v0.0.5-alpha
                external_links:
                        - ldap_server
                ports:
                        - 2049:2049
                environment:
                        - NFS_IPADDR_ALLOWED=${NFS_IPADDR_ALLOWED}
                volumes:
                        - nfs-server_public:/mnt/nfs_share/public
                        - nfs-server_home:/mnt/nfs_share/home
volumes:
        nfs-server_public:
        nfs-server_home:
