version: "3"
services:
        nfs_server:
                build: ./build
                image: drussell1974/nfs-server:release-v0.0.12-alpha
                external_links:
                        - ldap_server
                ports:
                        - 2049:2049
                environment:
                        - NFS_IPADDR_ALLOWED=${NFS_IPADDR_ALLOWED}
                        - NFS_PUBLIC_CONT=${NFS_PUBLIC_CONT}
                        - NFS_HOME_CONT=${NFS_HOME_CONT}
                volumes:
                        - ./nfs_share/public:${NFS_PUBLIC_CONT}
                        - ./nfs_share/home:${NFS_HOME_CONT}

