version: "3"
services:
        nfs_server:
                build: ./build
                image: drussell1974/nfs-server
                ports:
                        - 2049:2049
                environment:
                        - NFS_IPADDR_ALLOWED:${NFS_IPADDR_ALLOWED}
                volumes:
                        - "/media/dave/My\ Passport/home/:/mnt/nfs_share"
